language: node_js
node_js:
- '4.3'
script:
- npm install
- npm test
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: XBsHbD5oCZJkwoZOMwfq7rykMJnM/5Ix2G8AfzsGOq3Ac/8W/RTgd+urEeza4YtsfzX8PpRyhTBHaIFYsejYiKH6RRjcDJ35bwNA0HybFIGk70N+2gEDvHL3GyFlYgnKX6eyABuGCPG+LMx+P7ecdzjXbfBFjoiVynWqCKllVw6E926JEkEboY9ahev1/OqfP/cERfEJLMA9GIyjp+JHOomKSe1nKfQj1cdqpYBQPno0+D748fDdEU9Z9u/X5TuoNBnEvUSllTzjCyb4+VOMPDjO6DQICkE8CVeUuFEmLP6AvZGp0fcE5Oe68NYkhVm5hSwFHrC2nyETvVNoy0KZh8I5fUZUrj2oai82bfe1eV8CvtRnDuA/RAJGoGXfBDighTy2uBJX50/NEN7qZbG0GhM+gV9lNpP46f0JA26CLredDEN1MABQFlqtdqHgAtPyw45PjGS+x1KP7mzjn4BSvjMYP4xHPLTHBhQ7R3dNcc009Ygf1NqItxq6/1W3ySaTHCGRGRTIOIrL36UotbpBo9Ize57FTQKLcYSEhIWZSvoCkXbh78Sbx0gc9sFXwAV00Qm+iaipS3LpKLsUsrkJNANFoySaV0YqfpC/W+ifNUTgELoHHwTfvDziHUogPfVwPbu72qRp3keTCXoaHU2iQRbv7S5HczJa/ue2xFF349I=
  - secure: FgspI6HgbAw+EPM2KPnRdAANpzlyy3OYbGBrSKBrGdaw18ktERhVoQSPYrwAsD5wHb6o5Y++R4Eg7qEFuKSgfjF4aYeIe2xlXO4ELiFNtkz7HNWRa8bfv8HsgNxKEH5GHWbkHWutlj9kCieA3ooH0Oay+6e9bHnIdemnoW1++qI+nipkme6gDIrROECm6EOutGnc53q14Q36EdTIBel1h571QXHSOhQ4k8SXTZ54ck13QJILFOk0BRjV2edkpYXjH7tnFSpmsV245otl38+Rq3i36izG3YNGYrdngfi7bM3Eo/hlegp6JfIyxImWz+/n7QRCfnHKWO/jtoRsyfHlHEYaduc/rkD6vPBFhuptXEbvg2g0DjrsdPM9aWws7Z4OPA7KEi6N/kzdhDtxlgOGNHUPS6knNANodUdBtd1yCQ9LxGe7OVJqXHrrlDn003ksepVdpVGEKl+7X7BCdiVnW0jL6GGCsP1SZ3zPx/EOnyfFGKTFXcuvDYZMS0i64Mw81G7f4ILcjvGrhzrnYrn8MDf5EW/h6LAxUpiiPrhl9h5NBIuJiV1qF744HpnHVC/gL+Xp+XBQBRjbPEfsh6H4MI576lgvOf7myb/HXB00EgoYvH4mMDwPih/IzBekgOhzm3ph10T2bmfe7nyKVufm51OSEHyQ5qj3BMCefTqGA9w=
