---
swagger: "2.0"
info:
  version: "2016-05-06T10:09:48Z"
  title: Front pressed
  description: Server-less API for front pressed time
schemes:
- "https"
paths:
  /{environment}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "path"
        in: "query"
        required: true
        type: "string"
      - name: "environment"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        uri: "not sure"
        type: "aws"
definitions:
  Empty:
    type: "object"
