swagger: '2.0'
info:
    title: Front pressed
    description: Server-less API for front pressed time
    version: '1.0.0'
schemes:
    - https
produces:
    - application/json
paths:
    /{environment}:
        get:
            summary: Pressed time of live fronts
            responses:
                200:
                    description: Pressed date in ISO 8601
                    schema:
                        type: object
                        properties:
                            date:
                                type: string
                                format: date-time
                            status:
                                type: string
        parameters:
            - name: environment
              in: path
              description: Live or draft environment
              required: true
              type: string
              enum:
                  - live
                  - draft
            - name: path
              in: query
              description: Front path
              required: true
              type: string
